name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust according to your default branch name

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --disable-warnings

  docker-build:
    runs-on: ubuntu-22.04
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: sree095docker
          password: Hyderabad1995!

      - name: Build Docker image
        run: |
          docker build -t sree095docker/chat-app .

      - name: Push Docker image
        run: |
          docker push sree095docker/chat-app
